using UnityEngine;

/// <summary>
/// This class was auto generated by ResourceAtlasCreator.tt. Any changes made here
/// will most likely get replaced. Please make changes to the generator.
/// </summary>
public class TestingState : BaseState
{
	#region FIELDS & PROPERTIES

	public override bool isPassive
	{
		get { return True; }
	}
	
		public Action OnPushed = null;
	public Action OnPopped = null;
			
	#endregion
	
	#region METHODS

	#region ABSTRACT METHODS

	protected override void Pushed()
	{
			if(OnPushed != null)
		{
			OnPushed.Invoke();
		}
		}

	protected override void Popped()
	{
			if(OnPopped != null)
		{
			OnPopped.Invoke();
		}
		}

	protected override void Update()
	{
		}

	#endregion

	#endregion
}